# Generated by Django 4.2.7 on 2024-06-16 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todolist_user_alter_todolist_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='goods_images', verbose_name='Фотографія'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='created',
            field=models.DateField(default='16-06-2024'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='due_date',
            field=models.DateField(),
        ),
    ]
