# Generated by Django 4.2.7 on 2024-06-16 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_todolist_image_alter_todolist_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='category',
            field=models.ForeignKey(default='In progress', on_delete=django.db.models.deletion.PROTECT, to='todo.category'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='created',
            field=models.DateField(default='2024-06-16'),
        ),
    ]
