# Generated by Django 4.2.7 on 2024-06-16 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_alter_todolist_category_alter_todolist_created_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolist',
            old_name='category',
            new_name='done',
        ),
    ]
