# Generated by Django 4.2.7 on 2024-06-16 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_rename_category_todolist_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Фотографія'),
        ),
    ]
